### PR TITLE
Error in class namespace parameter

### PR DESCRIPTION
**Pull request by jonthorne**

### CODE REVIEW

**Comment by kunicmarko20** [comment]
@jonthorne thank you for catching this, could you fix the tests also, there is the same typo [here](https://github.com/kunicmarko20/SimpleConfigurationBundle/blob/v1.x/Tests/DependencyInjection/SimpleConfigurationExtensionTest.php#L16) and I can merge it.

**Comment by jonthorne** [comment]
No problem. Done.

On 24 Nov 2017, at 2:47 pm, Marko Kunic <notifications@github.com> wrote:

@jonthorne <https://github.com/jonthorne> thank you for catching this, could you fix the tests also, there is a same typo here <https://github.com/kunicmarko20/SimpleConfigurationBundle/blob/v1.x/Tests/DependencyInjection/SimpleConfigurationExtensionTest.php#L16> and I can merge it

**Comment by kunicmarko20** [comment]
@jonthorne I did not mean for you to create another PR, just add a commit to your branch `jonthorne:patch-1` and then it will be committed to this one because now both PRs are failing.

**Comment by jonthorne** [comment]
sorry, will fix it.

On 24 Nov 2017, at 2:52 pm, Marko Kunic <notifications@github.com> wrote:

@jonthorne <https://github.com/jonthorne> I did not mean for you to create another PR, just add a commit to your branch jonthorne:patch-1 and then it will be committed to this one because now both PRs are failing.

**Comment by kunicmarko20** [comment]
@jonthorne Thaks for closing that other PR, now just commit that typo fix in the test to the branch you used for this PR (`jonthorne:patch-1`).

**Comment by kunicmarko20** [comment]
Thanks @jonthorne

**Pull request merged**
